#!/usr/bin/env ansible-playbook
---
# vim:ff=unix ts=2 sw=2 ai expandtab

- name: build vim from source code
  hosts: localhost
  tasks:

    - name: enable deb-src in sources.list
      become: yes
      replace:
        path: /etc/apt/sources.list
        regexp: '^# deb-src (.*)$'
        replace: 'deb-src \1'
        backup: yes

    - name: apt install build deps
      become: yes
      apt:
        name: vim
        update_cache: yes
        state: build-dep

    - name: apt install extra deps
      become: yes
      apt:
        name:
          - xsel
          - xclip
          - libx11-dev
          - libxtst-dev
          - libxt-dev
          - libsm-dev
          - libxpm-dev
          - vim-gnome

    - name: get latest vim code
      git:
        repo: 'https://github.com/vim/vim.git'
        dest: '/tmp/vim'
        clone: yes
        update: yes
        force: yes
        version: master

    - name: make distclean
      shell: make distclean
      args:
        chdir: '/tmp/vim'

    - name: config vim
      shell: >
          ./configure
          --with-x
          --with-features=huge
          --enable-gui=gtk3
          --enable-multibyte
          --enable-python3interp
          --enable-pythoninterp
          --enable-rubyinterp
          --enable-perlinterp
          --enable-luainterp
          --enable-cscope
      args:
        chdir: '/tmp/vim'

    - name: make vim
      shell: make
      args:
        chdir: '/tmp/vim'

    - name: make install vim
      become: true
      shell: make install
      args:
        chdir: '/tmp/vim'

    - name: show version
      command: vim --version
