#!/usr/bin/env ansible-playbook
---
# vim:ff=unix ts=2 sw=2 ai expandtab

- hosts: vim
  tasks:

    - name: apt install deps
      become: yes
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - xorg-dev  # for +clipboard
        - xsel  # for vim clipboard in vscode
        - exuberant-ctags  # for tagbar
        - silversearcher-ag  # ag and ctrlp
        - shellcheck  # help to check shell script

    - name: pip install deps
      become: yes
      pip:
        requirements: "{{ playbook_dir }}/../requirements.txt"
