#!/usr/bin/env ansible-playbook
---
# vim:ff=unix ts=2 sw=2 ai expandtab

- hosts: vim
  tasks:

    - name: apt install deps
      become: yes
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - libx11-dev
        - libxtst-dev
        - xorg-dev  # for +clipboard
        - xsel  # for vim clipboard in vscode
        - exuberant-ctags  # for tagbar
        - silversearcher-ag  # ag and ctrlp
        - shellcheck  # help to check shell script
        - libncurses-dev  # required to build vim

    - name: get latest vim code
      git:
        repo: 'https://github.com/vim/vim.git'
        dest: '/tmp/vim'
        clone: yes
        update: yes
        force: yes
        version: master

    - name: make distclean
      shell: make distclean
      args:
        chdir: '/tmp/vim'

    - name: config vim
      shell: >
          ./configure --with-x
          --enable-gui=auto
          --enable-pythoninterp
          --enable-python3interp
          --enable-rubyinterp
      args:
        chdir: '/tmp/vim'

    - name: make vim
      shell: make
      args:
        chdir: '/tmp/vim'

    - name: make install vim
      become: true
      shell: make install
      args:
        chdir: '/tmp/vim'

    - name: show version
      command: vim --version
