#!/usr/bin/env ansible-playbook
---
# vim:ff=unix ts=2 sw=2 ai expandtab

- hosts: vim
  tasks:

    - name: apt install deps
      become: yes
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - libxt-dev
        - libx11-dev
        - libxpm-dev
        - libxtst-dev
        - libcairo2-dev
        - libncurses-dev
        - libgnomeui-dev
        - xorg-dev  # for +clipboard
        - xsel  # for vim clipboard in vscode
        - exuberant-ctags  # for tagbar
        - silversearcher-ag  # ag and ctrlp
        - shellcheck  # help to check shell script
        - python-dev
        - python3-dev
        - ruby-dev

    - name: get latest vim code
      git:
        repo: 'https://github.com/vim/vim.git'
        dest: '/tmp/vim'
        clone: yes
        update: yes
        force: yes
        version: master

    - name: make distclean
      shell: make distclean
      args:
        chdir: '/tmp/vim'

    - name: config vim
      shell: >
          ./configure
          --with-x
          --with-features=huge
          --enable-gui=gtk3
          --enable-multibyte
          --enable-python3interp
          --enable-pythoninterp
          --with-python-config-dir=/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu
          --enable-rubyinterp
          --enable-perlinterp
          --enable-luainterp
          --enable-cscope
      args:
        chdir: '/tmp/vim'

    - name: make vim
      shell: make
      args:
        chdir: '/tmp/vim'

    - name: make install vim
      become: true
      shell: make install
      args:
        chdir: '/tmp/vim'

    - name: show version
      command: vim --version
